services:
  cv-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv-manager
    restart: unless-stopped
    ports:
      - 8000:8000

  cv-manager-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - cv-manager