[project]
name = "cv-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.1",
    "django-cors-headers>=4.9.0",
    "django-jazzmin>=3.0.1",
    "djangorestframework>=3.16.1",
    "pillow>=12.1.0",
]
